let quotes = [
"“Organisms don't think of CO2 as a poison. Plants and organisms that make shells, coral, think of it as a building block.”\n– Janine Benyus",
"“Under the White Cliff’s battlemented crown, Hushed to a depth of more than Sabbath peace.”\n– William Wordsworth",
"“Never again can I gaze upon the beauty spots of the Earth and enjoy them as being the finest thing I have ever seen. Crater Lake is above them all.”\n– Jack London",
"“Like to the apples on the Dead Sea’s shore, all ashes to the taste.”\n– Lord Byron",
"“It is not the mountain we conquer but ourselves.”\n– Sir Edmund Hillary",
"“The natural history of this archipelago is very remarkable: it seems to be a little world within itself.”\n– Charles Darwin",
"“As it turns out, Mount Kilimanjaro is not wi-fi enabled, so I had to spend two weeks in Tanzania talking to the people on my trip.”\n– Nancy Bonds",
"“The Pantanal is the most complex intertropical alluvional plain of the planet and perhaps the least known area of the world.”\n– Aziz Ab’Saber",
"“But as I headed into the heart of New Zealand’s fiordland that same child-like feeling, long lost, of pure unadulterated awe came rushing back. I knew the road to Milford Sound was good – but this good?”\n– Darroch Donald",
"“Several closely situated granite peaks resembling tiger’s teeth dramatically soar about a kilometer into the sky”\n– Howard Hillman",
"“Tsingy is a 250-square-mile tiger trap made up on massive obelisks riddled with jagged spears. And yes, they will cut your pretty face.”\n– Budd Erickson",
"“Yosemite Valley, to me, is always a sunrise, a glitter of green and golden wonder in a vast edifice of stone and space.”\n– Ansel Adams",
"“No man ever wetted clay and then left it, as if there would be bricks by chance and fortune.” \n- Plutarch",
"“I thought clay must feel happy in the good potter’s hand.” \n– Janet Fitch",
"“If there are no dogs in Heaven, then when I die I want to go where they went.” \n- Will Rogers",
"“I am fond of pigs. Dogs look up to us. Cats look down on us. Pigs treat us as equals.” \n- Winston S. Churchill",
"“Who deserves more credit than the wife of a coal miner?” \n– Merle Travis",
"“When you find yourself in a hole, quit digging.” \n- Will Rogers",
"“Vessels large may venture more, but little boats should keep near shore.” \n-Benjamin Franklin",
"“It is not that life ashore is distasteful to me. But life at sea is better.” \n– Sir Francis Drake",
"“I don’t believe in astrology; I’m a Sagittarius and we’re skeptical.” \n– Arthur C. Clarke",
"“A physician without a knowledge of astrology has no right to call himself a physician.” \n- Hippocrates",
"“Thousands have lived without love, not one without water.” \n-W. H. Auden",
"“The man who has grit enough to bring about the afforestation or the irrigation of a country is not less worthy of honor than its conqueror.” \n– Sir John Thomson",
"“I shot an arrow into the air. It fell to earth, I knew not where.” \n– Henry Wadsworth Longfellow",
"“May the forces of evil become confused while your arrow is on its way to the target.” \n– George Carlin",
"“Writing means sharing. It’s part of the human condition to want to share things – thoughts, ideas, opinions.” \n– Paulo Coelho",
"“Writing is easy. All you have to do is cross out the wrong words.” \n-Mark Twain",
"“Each of us is carving a stone, erecting a column, or cutting a piece of stained glass in the construction of something much bigger than ourselves.”\n– Adrienne Clarkson",
"“When wasteful war shall statues overturn, and broils root out the work of masonry.” \n– William Shakespeare",
"“Bronze is the mirror of the form, wine of the mind.” \n– Aeschylus",
"“I’m also interested in creating a lasting legacy … because bronze will last for thousands of years.” \n- Richard MacDonald",
"“Sometimes the wheel turns slowly, but it turns.” \n– Lorne Michaels",
"“Don’t reinvent the wheel, just realign it.” \n– Anthony D’Angelo",
"“And all I ask is a tall ship and a star to steer her by.” \n– John Masefield",
"“Set your course by the stars, not by the lights of every passing ship.” \n– Omar Bradley",
"“Wealth consists not in having great possessions, but in having few wants.” \n- Epictetus",
"“Money, if it does not bring you happiness, will at least help you be miserable in comfort.”\n – Helen Gurley Brown",
"“No hour of life is wasted that is spent in the saddle.” \n– Winston Churchill",
"“A man on a horse is spiritually as well as physically bigger than a man on foot.” \n– John Steinbeck",
"“The Lord made us all out of iron. Then he turns up the heat to forge some of us into steel.” \n– Marie Osmond",
"“Everything has its limit – iron ore cannot be educated into gold.” \n– Mark Twain",
"“I cannot imagine any condition which would cause a ship to founder … Modern shipbuilding has gone beyond that.” \n– Capt. E.J. Smith, RMS Titanic",
"“There is nothing but a plank between a sailor and eternity.”\n – Thomas Gibbons",
"“Without mathematics, there’s nothing you can do. Everything around you is mathematics. Everything around you is numbers.” \n– Shakuntala Devi",
"“If I were again beginning my studies, I would follow the advice of Plato and start with mathematics.” \n– Galileo Galilei",
"“Create with the heart; build with the mind.” \n– Criss Jami",
"“The four building blocks of the universe are fire, water, gravel and vinyl.” \n– Dave Barry",
"“One man’s ‘magic’ is another man’s engineering.” \n– Robert Heinlein",
"“Normal people … believe that if it ain’t broke, don’t fix it. Engineers believe that if it ain’t broke, it doesn’t have enough features yet.” \n– Scott Adams",
"“Tactics mean doing what you can with what you have.” \n– Saul Alinsky",
"“Strategy requires thought; tactics require observation.” \n– Max Euwe",
"“We are all apprentices in a craft where no one ever becomes a master.” \n– Ernest Hemingway",
"“There is no easy way to train an apprentice. My two tools are example and nagging.” \n– Lemony Snicket",
"“Few inventions have been so simple as the stirrup, but few have had so catalytic an influence on history.” \n– Lynn White Jr.",
"“Betwixt the stirrup and the ground, Mercy I asked, mercy I found.” \n– William Camden",
"“I’d imagine the whole world as one big machine. Machines never come with any spare parts, you know. They always come with the exact amount they need.” \n– Hugo Cabret",
"“Remember that people break down, too, not just machinery.” \n– Gregory Benford",
"The purpose of education is to replace an empty mind with an open one.” \n– Malcolm Forbes",
"“It is the mark of an educated mind to be able to entertain a thought without accepting it.” \n- Aristotle",
"“Blast – Build – Battle” \n– Motto of the U.S. 16th Engineer Brigade",
"“The more science intervenes in warfare, the more will be the need for engineers in the field armies; in the late war there were never enough sappers at any time.” \n– Bernard Montgomery",
"“Rocks in my path? I keep them all. With them I shall build my castle.” \n– Nemo Nox",
"“If you see a castle under fog, you must walk there to meet the extraordinary dreams.” \n– Mehmet Murat Ildan",
"“Not all who wander are lost.” \n– J.R.R. Tolkien",
"“People can have the Model T in any color – so long as it’s black.” \n– Henry Ford",
"“What can be labeled, packaged, mass produced is neither truth nor art.” \n– Marty Rubin",
"“If you owe the bank $100 that’s your problem. If you owe the bank $100 million, that’s the bank’s problem.” \n– J. Paul Getty",
"“I saw a bank that said ’24-Hour Banking,’ but I didn’t have that much time.” \n– Steven Wright",
"“The real use of gunpowder is to make all men tall.” \n– Thomas Carlyle",
"“Man is a military animal, glories in gunpowder, and loves parades.” \n– Philip Bailey",
"“The pen might not be mightier than the sword, but maybe the printing press is heavier than the siege weapon. Just a few words can change everything.” \n– Terry Pratchett",
"“What gunpowder did for war the printing press has done for the mind.” \n- Wendell Phillips",
"“There is little man has made that approaches anything in nature, but a sailing ship does.” \n– Allan Villiers",
"“It’s not the towering sails, but the unseen wind that moves a ship.” \n– English Proverb",
"“Astronomy compels the soul to look upwards and leads us from this world to another.” \n- Plato",
"“Astronomy’s much more fun when you’re not an astronomer.” \n– Brian May",
"“And first Hephaestus makes a great and massive shield … And he forged on the shield two noble cities.” \n– Homer",
"“Don’t judge someone until you’ve stood at his forge and worked with his hammer.” \n– Rick Riordan",
"“The lowest is to attack a city. Siege of a city is only done as a last resort.” \n– Sun Tzu",
"“All the best romances bloom in the midst of a good siege.” \n– Miles Cameron",
"“I think the human race made a big mistake at the beginning of the Industrial Revolution, we leaped for the mechanical things. People need the use of their hands to feel creative.” \n– Andre Norton",
"“The key words of violent economics are urbanization, industrialization, centralization, efficiency, quantity, speed.” \n– E.F. Schumacher",
"“Claims that cannot be tested, assertions immune to disproof are veridically worthless, whatever value they may have in inspiring us or exciting our sense of wonder.” \n– Carl Sagan",
"“If facts don’t fit the theory, change the facts.” \n– Albert Einstein",
"“It’s one thing to surmise what happened, but we don’t speculate on that until ballistics confirms what happened …” \n– John Hansen",
"“Let’s get on our knees and pray. I don’t know to whom. Is there a patron saint of ballistics yet?” \n– Adam Savage",
"“However beautiful the strategy, you should occasionally look at the results.” \n– Winston Churchill",
"“No one starts a war – or rather, no one in his senses ought to do so – without first being clear in his mind what he intends to achieve by that war and how he intends to conduct it.” \n– Karl von Clausewitz",
"“It is arguable whether the human race have been gainers by the march of science beyond the steam engine.” \n– Winston Churchill",
"“Science owes more to the steam engine than the steam engine owes to science.” \n– Lawrence Henderson",
"“No innovation in the past 200 years has done more to save lives and improve health than the sanitation revolution triggered by the invention of the toilet.” \n– Sylvia Burwell",
"“Apart from the sanitation, the medicine, education, wine, public order, roads, the fresh water system, and public health … what have the Romans ever done for us?” \n– John Cleese",
"“Economics is a subject that does not greatly respect one’s wishes.” \n– Nikita Khrushchev",
"“You and I come by road or rail, but economists travel on infrastructure.” \n- Margaret Thatcher",
"“Bolt actions speak louder than words.” \n– Craig Roberts",
"“Never criticize a rifleman until you have walked a mile in his shoes. That way, he’ll be barefoot and you’ll be out of range.” \n– The 2nd Target Company",
"“For once you have tasted flight you will walk the earth with your eyes turned skywards, for there you have been and there you will long to return.” \n– Leonardo da Vinci",
"“If you can walk away from a landing, it’s a good landing. If you use the airplane the next day, it’s an outstanding landing.” \n– Chuck Yeager",
"“For a machine to run smoothly and predictably, its parts must be standard and hence replaceable.” \n– Charles Eisenstein",
"“Many of us take better care of our automobiles than we do of our own bodies … yet the auto has replaceable parts.” \n– B.J. Palmer",
"“The best steel doesn’t always shine the brightest.” \n– Joe Abercrombie",
"“There are three things extremely hard: steel, a diamond, and to know one’s self.” \n– Benjamin Franklin",
"“If it weren’t for electricity, we’d all be watching television by candlelight.” \n– George Gobel",
"“Benjamin Franklin may have discovered electricity, but it was the man who invented the meter who made the money.” \n– Earl Wilson",
"“A world without radio is a deaf world.” \n– Ernest Yeboah",
"“Radio is the theater of the mind; television is the theater of the mindless.” \n– Steve Allen",
"“Chemistry is the dirty part of physics.” \n– Peter Reiss",
"“Chemists do not usually stutter. It would be very awkward if they did, seeing that they have at times to get out such words as methylethylamylophenylium.” \n– Sir William Crookes",
"“The cars haven’t advanced that much since we were kids. When you boil it down, it’s still a gas combustion engine.” \n– Dana Brunetti",
"“I have always considered that the substitution of the internal combustion engine for the horse marked a very gloomy milestone in the progress of mankind.” \n– Winston Churchill",
"“Sure, jets are fast and economical, but, oh my, what fun we’ve lost and what leisure we’ve sacrificed in the race for efficiency.” \n– Ginger Rogers",
"“If God had really intended men to fly, He’d make it easier to get to the airport.” \n– George Winters",
"“Rocket science has been mythologized all out of proportion to its true difficulty.” \n– John Carmack",
"“When you launch a rocket, you’re not really flying that rocket. You’re just sort of hanging on.” \n– Michael P. Anderson",
"“Untutored courage is useless in the face of educated bullets.” \n– George Patton",
"“Aim for the moon. If you miss, you may hit a star.” \n– W. Clement Stone",
"“Better to fight for something than live for nothing.” \n- George S. Patton",
"“The chief incalculable in war is the human will.” \n- B.H. Liddell Hart.",
"“In the hierarchy of the major poetic substances, plastic figures as a disgraced material, lost between the effusiveness of rubber and the flat hardness of metal.” \n– Roland Barthes",
"“Nothing on this earth lasts forever. Except maybe plastic.” \n– Patricia Dunn",
"“To err is human, but to really foul things up you need a computer.” \n– Paul R. Ehrlich",
"“The good thing about computers is that they do what you tell them to do. The bad news is that they do what you tell them to do.” \n– Ted Nelson",
"“If you go on with this nuclear arms race, all you are going to do is make the rubble bounce.” \n– Winston Churchill",
"“Leave the atom alone.” \n- E. Y. Harburg",
"“There’s so much plastic in this culture that vinyl leopard skin is becoming an endangered synthetic.” \n– Lily Tomlin",
"“There may be no forgiveness for polyester. On this one matter, Satan and the Lord are in agreement.” \n– Joe Hill",
"“Mr. Watson… Come here… I want to see you.” \n- Alexander Graham Bell",
"“The single biggest problem in communication is the illusion that it has taken place.” \n– George Bernard Shaw",
"“A satellite has no conscience.” \n– Edward R. Murrow",
"“Right now there are thirty-one satellites zipping around the world with nothing better to do than help you find your way to the grocery store.” \n– Ed Burnette",
"“If you do not change direction, you may end up where you were heading.” \n– Lao Tzu",
"“I love watching my mom argue with the GPS on the way home.” \n– Isabelle Fuhrman",
"“When God said, ‘Let there be light,’ he surely must have meant perfectly coherent light.” \n– Charles Townes",
"“I’m a big laser believer – I really think they are the wave of the future.” \n– Courteney Cox",
"“All material things seem to have been composed of the hard and solid particles … variously associated with the first Creation by the counsel of an Intelligent Agent.” \n– Isaac Newton",
"“It is obvious that while science is struggling to bring Heaven to Earth some men are using its materials in the construction of Hell.” \n– Herbert Hoover",
"“I would say invisibility would be sort of a fun power to have just to see what it was like to move through the world and not be looked at.” \n- Kevin Bacon",
"“In art and dream may you proceed with abandon. In life may you proceed with balance and stealth.” \n– Patti Smith",
"“Robotics has been around forever, and it’s been the next big thing forever, and it is so exciting and compelling that it’s easy to get carried away.” \n– Colin Angle",
"“I’ll be back.”",
"“If technology is the engine of change, then nanotechnology is the fuel for humanity’s future.” \n– Natasha Vita-More",
"“Many, many rules had begun to bend at the hand of nanotechnology … This produced a lot of good, and a lot of bad.” \n– Matt Spire",
"“There is nothing like a dream to create the future.” \n– Victor Hugo",
"“Even though the future seems far away, it is actually beginning right now.” \n– Mattie Stepanek",
"“I am a big proponent of harnessing the power of fusion – from 93 million miles away. Fusion is done by our sun really, really well and for free. Here on Earth in reactors, not so much.” \n– Joe Romm",
"“When we look up at night and view the stars, everything we see is shining because of distant nuclear fusion.” \n– Carl Sagan",
"“It is not wisdom but authority that makes a law.” \n– Thomas Hobbes",
"“At his best, man is the noblest of all animals; separated from law and justice he is the worst.” \n– Aristotle",
"“Without craftsmanship, inspiration is a mere reed shaken in the wind.”\n – Johannes Brahms",
"“Skill without imagination is craftsmanship and gives us many useful objects such as wickerwork picnic baskets.” \n– Tom Stoppard",
"“Every nation lives by exchanging.” \n– Adam Smith",
"“That’s the positive aspect of trade I suppose. The world gets stirred up together.” \n– Isabel Hoving",
"“Bravery is being the only one who knows you’re afraid.” \n— Colonel David Hackworth",
"“I don’t underrate the value of military knowledge, but if men make war in slavish obedience to rules, they will fail.” \n– Ulysses S. Grant",
"“A strong economy begins with a strong, well-educated workforce.”\n– Bill Owens",
"“It is equally important to have a happy and engaged workforce as it is to have a profitable bottom line.” \n– Vern Dosch",
"“Look back over the past, with its changing empires that rose and fell, and you can foresee the future, too.” \n- Marcus Aurelius",
"“It was luxuries like air conditioning that brought down the Roman Empire. With air conditioning their windows were shut; they couldn’t hear the barbarians coming.”\n – Garrison Keillor",
"“Mysticism is the mistake of an accidental and individual symbol for a universal one.” \n– Ralph Waldo Emerson",
"“I like to say I practice militant mysticism. I’m absolutely sure of some things that I don’t quite know.” \n– Rob Bell",
"“If bread is the first necessity of life, recreation is a close second.” \n– Edward Bellamy",
"“People who cannot find time for recreation are sooner or later to find time for illness.” \n– John Wanamaker",
"“Politics is the art of the possible, the attainable – the art of the next best.” \n– Otto von Bismarck",
"“Divide and rule, a sound motto. Unite and lead, a better one.” \n– Johann Wolfgang von Goethe",
"“The poets have been mysteriously silent on the subject of cheese.” \n- G. K. Chesterton",
"“All the world’s a stage, and all the men and women merely players.” \n– William Shakespeare",
"“If it’s natural to kill, how come men have to go into training to learn how?” \n– Joan Baez",
"“Those who in quarrels interpose, must often wipe a bloody nose.” \n- John Gay",
"“Invincibility lies in the defense; the possibility of victory in the attack.” \n– Sun Tzu",
"“Defense is superior to opulence.” \n– Adam Smith",
"“I've lived through some terrible things in my life, some of which actually happened.” \n- Mark Twain",
"“History is the version of past events that people have decided to agree upon.” \n– Napoleon Bonaparte",
"“We can no more have exact religious thinking without theology, than exact mensuration and astronomy without mathematics, or exact iron-making without chemistry.” \n– John Hall",
"“Man suffers only because he takes seriously what the gods made for fun.” \n– Alan W. Watts",
"“A good navy is not a provocation to war. It is the surest guaranty of peace.” \n – Theodore Roosevelt",
"“The Navy has both a tradition and a future – and we look with pride and confidence in both directions.” \n– Arleigh Burke",
"“In democracy it’s your vote that counts; in feudalism it’s your count that votes.” \n– Mogens Jallberg",
"“With the advance of feudalism came the growth of iron armor, until, at last, a fighting-man resembled an armadillo.” \n– John Boyle O’Reilly",
"“It’s all papers and forms, the entire civil service is like a fortress made of papers, forms and red tape.” \n – Alexander Ostrovsky",
"“The taxpayer - that's someone who works for the federal government but doesn't have to take the civil service examination.” \n - Ronald Reagan",
"“In peace one is despoiled by mercenaries; in war by one’s enemies.” \n– Niccolo Machiavelli",
"“Being a mercenary, though … Hey, we just go wherever there’s a mixture of money and trouble.” \n– Howard Tayler",
"“All that glisters is not gold; often have you heard that told.” \n– William Shakespeare",
"“There are very honest people who do not think that they have had a bargain unless they have cheated a merchant.” \n– Anatole France",
"“Every man should make his son learn some useful trade or profession, so that in these days of changing fortunes … they may have something tangible to fall back upon.” \n– Phineas T. Barnum",
"“You can’t go around arresting the Thieves’ Guild. I mean, we’d be at it all day!” \n– Terry Pratchett",
"“I conclude then this point touching upon the power of kings with this axiom of divinity, That as to dispute what God may do is blasphemy … so it is sedition to dispute what a king may do.” \n– King James I",
"Amory Blaine inherited from his mother every trait, except the stray inexpressible few, that made him worth while.",
"“Listen, strange women lying in ponds distributing swords is no basis for a system of government … You can’t expect to wield supreme power just ‘cause some watery tart threw a sword at you!” \n– Monty Python",
"“The day we stop exploring is the day we commit ourselves to live in a stagnant world, devoid of curiosity, empty of dreams.” \n– Neil deGrasse Tyson",
"“We shall not cease from exploration, and the end of all our exploring will be to arrive where we started and know the place for the first time.” \n– T.S. Eliot",
"“The four characteristics of humanism are curiosity, a free mind, belief in good taste, and belief in the human race.” \n– E.M. Forster",
"“You must not lose faith in humanity. Humanity is like an ocean; if a few drops of the ocean are dirty, the ocean does not become dirty” \n - Mahatma Gandhi",
"“In diplomacy there are two kinds of problems: small ones and large ones. The small ones will go away by themselves, and the large ones you will not be able to do anything about.” \n– Patrick McGuinness",
"“A diplomat is a man who always remembers a woman’s birthday but never remembers her age.” \n– Robert Frost",
"“I don't like to commit myself about Heaven and Hell, you see, I have friends in both places.” \n- Mark Twain",
"“The three great elements of modern civilization: gun powder, printing, and the Protestant religion.” \n– Thomas Carlyle",
"“In a market economy, however, the individual has some possibility of escaping from the power of the state.” \n– Peter Berger",
"“Having seen a non-market economy, I suddenly understood much better what I liked about a market economy.” \n– Esther Dyson",
"“New opinions are always suspected, and usually opposed, without any other reason but because they are not already common.” \n– John Locke",
"“Whatever is contrary to nature is contrary to reason, and whatsoever is contrary to reason is absurd.” \n– Baruch Spinoza",
"“Remember that politics, colonialism, imperialism and war also originated in the human brain.” \n– Vilayanur Ramachandran",
"“Colonialism. The enforced spread of the rule of reason. But who is going to spread it among the colonizers?” \n– Anthony Burgess",
"“Improvement makes straight roads; but the crooked roads without improvement are roads of Genius.” \n– William Blake",
"“A common mistake that people make when trying to design something completely foolproof is to underestimate the ingenuity of complete fools.” \n– Douglas Adams",
"“It is nationalism which engenders nations, and not the other way round.” \n– Ernest Gellner",
"“Human nature, as manifested in tribalism and nationalism, provides the momentum of the machinery of human evolution.” \n– Arthur Keith",
"“Opera is when a guy gets stabbed in the back and, instead of bleeding, he sings.” \n- Robert Benchley",
"“It [ballet] projects a fragile kind of strength and a certain inflexible precision.” \n– Ayn Rand",
"“Had I been present at the Creation, I would have given some useful hints for the better ordering of the universe.” \n- Nelson Algren",
"“In all works on Natural History, we constantly find details of the marvelous adaptation of animals to their food, their habits, and the localities in which they are found.” \n– Alfred Wallace",
"“War is hell.” \n– William Tecumseh Sherman",
"“I only understand friendship or scorched earth.” \n– Roger Ailes",
"“It’s the Industrial Revolution and the growth of urban concentrations that led to a sense of anonymity.” \n– Vint Cerf",
"“What I like about cities is that everything is king size, the beauty and the ugliness.” \n– Joseph Brodsky",
"“The inherent vice of capitalism is the unequal sharing of blessings; the inherent virtue of socialism is the equal sharing of miseries.” \n– Winston Churchill",
"“Always try to rub up against money, for if you rub up against money long enough, some of it may rub off on you.” \n- Damon Runyon",
"“Water and air, the two essentials on which life depends, have become global garbage cans.” \n– Jacques Yves Cousteau",
"“Destroying rainforest for economic gain is like burning a Renaissance painting to cook a meal.” \n– Edward Wilson",
"“The effect of the mass media is not to elicit belief but to maintain the apparatus of addiction.” \n– Christopher Lasch",
"“If you don't read the newspaper, you're uninformed. If you read the newspaper, you're mis-informed.” \n-Mark Twain",
"“When they are preparing for war, those who rule by force speak most copiously about peace until they have completed the mobilization process.” \n– Stefan Zweig",
"“In order to rally people, governments need enemies … if they do not have a real enemy, they will invent one in order to mobilize us.” \n– Nhat Hanh",
"“The release of atom power has changed everything except our way of thinking…the solution to this problem lies in the heart of mankind. If only I had known, I should have become a watchmaker.” \n– Albert Einstein",
"”The children of the nuclear age, I think, were weakened in their capacity to love. Hard to love, when you’re bracing yourself for impact.” \n– Martin Amis",
"“It has been demonstrated that no system, not even the most inhuman, can continue to exist without an ideology.” \n– Joe Slovo",
"“Slowly, ideas lead to ideology, lead to policies that lead to actions.” \n– Nandan Nilekani",
"“Why is a woman to be treated differently? Woman suffrage will succeed, despite this miserable guerrilla opposition.” \n– Victoria Woodhull",
"“Men, their rights, and nothing more; women, their rights, and nothing less.” \n– Susan B. Anthony",
"“Only the mob and the elite can be attracted by the momentum of totalitarianism itself. The masses have to be won by propaganda.” \n– Hannah Arendt",
"“The ultimate end of any ideology is totalitarianism.” \n– Tom Robbins",
"“There’s class warfare, all right, but it’s my class, the rich class, that’s making war … and we’re winning.”\n – Warren Buffett",
"“The class struggle necessarily leads to the dictatorship of the proletariat.” \n– Karl Marx",
"“From Stettin in the Baltic to Trieste in the Adriatic, an iron curtain has descended across the continent.” \n– Winston Churchill",
"“The Cold War is not thawing; it is burning with a deadly heat.” \n– Richard Nixon",
"“If winning isn’t everything, why do they keep score?”\n – Vince Lombardi",
"“Sports do not build character. They reveal it.” \n- Heywood Broun",
"“A people without the knowledge of their past history, origin and culture is like a tree without roots.” \n– Marcus Garvey",
"“You don’t stumble upon your heritage. It’s there, just waiting to be explored and shared.” \n– Robbie Robertson",
"“A good plan violently executed right now is far better than a perfect plan executed next week.” \n- George S. Patton",
"“Never mind the maneuvers, just go straight at them.” \n- Horatio Nelson",
"“We choose to go to the moon in this decade and do the other things, not because they are easy, but because they are hard.” \n– John F. Kennedy",
"“NASA spent millions of dollars inventing the ball-point pen so they could write in space. The Russians took a pencil.” \n– Will Chabot",
"“It has been said that arguing against globalization is like arguing against the laws of gravity.”\n – Kofi Annan",
"“One day there will be no borders, no boundaries, no flags and no countries and the only passport will be the heart.” \n– Carlos Santana",
"“Which of all my important nothings shall I tell you first?” \n-Jane Austen",
"“Distracted from distraction by distraction!”\n – T.S. Eliot",
"“You can never plan the future by the past.” \n-Edmund Burke",
"“I never think of the future. It comes soon enough.”\n –Albert Einstein",
"He is as the fall of a thunderbolt to the lordly mountains,\nthe eagle to all the birds, the lion to the assemblies of wild beasts,\nDeath, in human form.",
"Oh, my heart, be thou content with the truth of thy suspicions. Learn now of my sire's decease and for a moment be thou calm.",
"Let me not then die ingloriously and without a struggle, but let me first do some great thing that shall be told among men hereafter.",
"For a friend with an understanding heart is worth no less than a brother.",
"I held up a fistful of sand and showed it to him, asking for as many years as grains in that pile. Foolish me! I forgot to ask they be years of youth.",
"Chance is all-powerful. Always cast your fishing hook; in the pond where you least expect it, you'll find a fish.",
"From the light came light, and from the dark came darkness, but from whence did they appear? Yin and yang combine to create all things, but which is the source, and which was born from it?",
"Time rolls ever forward without a pause,\nThe seasons cycle through spring and autumn.\nAs I watch the green fade all around me,\nI fear the sun setting on my youth.",
" A KNYGHT ther was, and that a worthy man,\nThat fro the tyme that he first bigan\nTo riden out, he loved chivalrie,\nTrouthe and honour, fredom and curteisie.",
"If I be she that may yow do gladnesse,\nFor every wo ye shal recovere a blisse';\nAnd him in armes took, and gan him kisse.",
"Flowers surround me, alone with my drink,\nI pour for myself, no companion to join me.\nI raise my glass and toast the full moon,\nWho shall with my shadow make us three.",
"She was dazzling—alight; it was agony to comprehend her beauty in a glance.",
"I fan myself in this most languid heat,\nThe forest invites one to lay all bare.\nI hang my hood upon a rocky crag,\nMy head exposed I bathe in fragrant air.",
"As a young boy my brother Nobunori studied the Chinese classics, and I liked to sit in and listen to his lessons. I found that even when he struggled to understand or memorize passages, I would find them remarkably easy. My father, a well-read man himself, often used to lament this fact, saying, 'Such a shame. Would that you were born a man!'",
"New grass, you don’t even know where to sprout and grow. How can I, a drop of dew, vanish away in the air leaving you alone?",
"Out of this Room there was a passage into the Emperor's Bed-Chamber, the Walls whereof were of Jet, and the Floor of black Marble; the Roof was of Mother of Pearl, where the Moon and Blazing-Stars were represented by white Diamonds, and his Bed was made of Diamonds and Carbuncles.",
"It is known that man has five Exterior Senses, and every sense is ignorant of each other; for the Nose knows not what the Eyes see, nor the Eyes what the Ears hear, neither do the Ears know what the Tongue tastes...",
"Doubt if you will, but the truth is that which I have told, and forever rests upon lies like oil over water.",
"And, being merry and young, they did not miss any chances of hearing about the beautiful maids of the city.",
"Thus it is necessary to note, men must be either enticed or snuffed out. For light offenses they avenge, grievous ones they cannot; therefore the offense done to a man must be such as to remove any fear of revenge.",
"It is necessary for the one who founds a republic, and sets laws in it, to presuppose all men evil, and always ready to put the maliciousness in their soul to use, every time they have a chance...",
"O, swear not by the moon, the inconstant moon,\nThat monthly changes in her circled orb,\nLest that thy love prove likewise variable.",
"To be, or not to be? That is the question—\nWhether ’tis nobler in the mind to suffer\nThe slings and arrows of outrageous fortune,\nOr to take arms against a sea of troubles,\nAnd, by opposing, end them?",
"And because she was so beautiful they called her Princess Goldilocks; for her hair was finer than gold, wonderfully fair, and it fell in ringlets to her feet.",
"“If you will be so good and generous as to let me free,” the dolphin went on, “I shall render you such real services in the course of my life that you will never need to repent of your kindness.”",
"Dreams, dreams! Where have you gone? How sweet you were.",
"Like some magistrate grown gray in office,\nCalmly he contemplates alike the just\nAnd unjust, with indifference he notes\nEvil and good, and knows not wrath nor pity.",
"“Villains!” I shrieked, “dissemble no more! I admit the deed! --tear up the planks! here, here! --It is the beating of his hideous heart!”",
"While I nodded, nearly napping, suddenly there came a tapping,\nAs of some one gently rapping, rapping at my chamber door.\n“’Tis some visitor,” I muttered, “tapping at my chamber door—\nOnly this and nothing more.”",
"“A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment.”",
"Know your own happiness. You want nothing but patience- or give it a more fascinating name, call it hope.",
"As soon as you trust yourself, you will know how to live.",
"“The human race is a monotonous affair. Most people spend the greatest part of their time working in order to live, and what little freedom remains so fills them with fear that they seek out any and every means to be rid of it.”",
"I beheld the wretch — the miserable monster whom I had created.",
"This intelligence brought us back from the prospect of paradise, held out after the lapse of an hundred thousand years, to the pain and misery at present existent upon earth.",
"Every life is many days, day after day. We walk through ourselves, meeting robbers, ghosts, giants, old men, young men, wives, widows, brothers-in-love. But always meeting ourselves.",
"One by one they were all becoming shades. Better pass boldly into that other world, in the full glory of some passion, than fade and wither dismally with age.",
"A Bird came down the Walk—\nHe did not know I saw—\nHe bit an Angleworm in halves\nAnd ate the fellow, raw.",
"Success is counted sweetest\nBy those who ne'er succeed.\nTo comprehend a nectar\nRequires sorest need.",
"“Pierre was right when he said that one must believe in the possibility of happiness in order to be happy, and I now believe in it. Let the dead bury the dead, but while I'm alive, I must live and be happy.”",
"All the girls in the world were divided into two classes: one class included all the girls in the world except her, and they had all the usual human feelings and were very ordinary girls; while the other class -herself alone- had no weaknesses and was superior to all humanity.",
"“Jim said that bees won't sting idiots, but I didn't believe that, because I tried them lots of times myself and they wouldn't sting me.”",
"He had discovered a great law of human action, without knowing it--namely, that in order to make a man or a boy covet a thing, it is only necessary to make the thing difficult to attain.",
"No one would have believed in the last years of the nineteenth century that this world was being watched keenly and closely by intelligences greater than man's and yet as mortal as his own...",
"Very simple was my explanation, and plausible enough - as many wrong theories are!",
"I am willing to serve my country, but my worship I reserve for Right which is far greater than my country. To worship my country as a god is to bring a curse upon it.",
"If some wanderer, leaving home, come here to watch the night and with bowed head listen to the murmur of the darkness, who is there to whisper the secrets of life into his ears if I, shutting my doors, should try to free myself from mortal bonds?",
"My dear Miss Glory, Robots are not human. Mechanically, they are more perfect than us, they possess an amazing rational intelligence, but they do not have any soul.",
"Great God of the Ants, thou hast let the victory prevail! I hereby name thee the Colonel.",
"Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win.",
"“From the heights of these pyramids, forty centuries look down on us.”\n– Napoleon Bonaparte",
"“Petra is a brilliant display of man’s artistry in turning barren rock into majestic wonder.”\n– Edward Dawson",
"“Church and State, Soul and Body, God and Man, are all one at Mont Saint Michel, and the business of all is to fight, each in his own way, or to stand guard for each other.”\n– Henry Adams",
"“The Great Ball Court is also very impressive. I would like to have seen them play a game, although it sounds like the end was pretty violent. I think it was safer to be a spectator.”\n– IslaDeb",
"“Can you imagine trying to talk six hundred people into helping you drag a fifty-ton stone eighteen miles across the countryside and muscle it into an upright position, and then saying, ‘Right, lads! Another twenty like that … and then we can party!”\n– Bill Bryson",
"“I sprang upon the swift ship in the form of a dolphin, pray to me as Apollo Delphinius; also the altar itself shall be called Delphinius and overlooked forever.”\n– Homer",
"“There were seven wonders in the world, and the discovery of the Terracotta Army, we may say, is the eighth miracle of the world.”\n– Jacques Chirac",
"“Everything here appears calculated to inspire kind and happy feelings, for everything is delicate and beautiful.”\n– Washington Irving",
"“Thus, the sculpture serves to give people one thought – ‘Everything is in God’s hands.’”\n– Sergey Semenov",
"“The first time I stepped onto the rooftop of the Potala Palace, I felt, as never before or since, as if I were stepping onto the rooftop of my being: onto some dimension of consciousness that I’d never visited before.”\n– Pico Iyer",
"“The ascent to the highest story is by stairs, and at their side are water engines, by means of which persons, appointed expressly for the purpose, are continually employed in raising water from the Euphrates into the garden.”\n– Strabo",
"“The whole palace complex is built along a central axis, the axis of the world, everything in the four directions suspend from this central point represented by these palaces.”\n– Jeffrey Riegel",
"“Museums are on the front lines of the fight for culture, of good with evil – in any case, of the fight against platitudes and primitiveness.”\n– Mikhail Piotrovsky, Director of the State Hermitage",
"“I ought to be jealous of the tower. She is more famous than I am.”\n– Gustave Eiffel",
"“At Rhodes was set up a Colossus of seventy cubits high, representing the Sun … the artist expended as much bronze on it as seemed likely to create a dearth in the mines.”\n– Philo of Byzantium",
"“This Lighthouse was the cynosure of all eyes.”\n– Henry David Thoreau",
"“An opera begins long before the curtain goes up and ends long after it has come down. It starts in my imagination, it becomes my life, and it stays part of my life long after I've left the opera house.”\n– Maria Callas",
"“King Solomon gave the Queen of Sheba all she desired and asked for; besides what he had given her out of his royal bounty. So she turned and went to her own country, she and her servants.”\n– 1 Kings, 10:13",
"“Don’t watch the big clock; do what it does. Keep going.”\n– Sam Levenson",
"“While the Colosseum stands, Rome shall stand; when the Colosseum falls, Rome shall fall; when Rome falls, the world shall fall.”\n– Saint Bede",
"“Down through its history, only three people have managed to silence the Maracana: the Pope, Frank Sinatra, and me.”\n– Alcides Ghiggia, Uruguayan soccer player",
"“The commonwealth of Venice in their armory have this inscription: ‘Happy is that city which in time of peace thinks of war.’”\n– Robert Burton",
"“The industrial heart of Germany practically stopped beating. Hardly anyone worked; hardly anything ran. The population of the Ruhr area … had to be supported by the rest of the country.”\n– Adam Fergusson",
"“In a dusty, bustling corner of the Indian state of Bihar, there is a magical place that one might think of as the hub of Buddhism.”\n– Visitor’s Guide, Bodh Gaya",
"“It is a beautiful and important monument and an international, inter-cultural treasure … Unless and until it can be shared by both religions in harmony – which would be a grand idea – it should remain a secular building honoring both religions who have made it beautiful.”\n– Ljubo Vujovic",
"“We can roam the bloated stacks of the Library of Alexandria, where all imagination and knowledge are assembled; we can recognize in its destruction the warning that all we gather will be lost.”\n– Alberto Manguel",
"“The clever men at Oxford... Know all that there is to be knowed. But they none of them know one half as much... As intelligent Mr. Toad!”\n– Kenneth Grahame",
"“Bolshoi Ballet is a universe of the imagination, a place of magic and enchantment, beauty and romance. Its many worlds vibrate with graceful dancers, glorious music, and sumptuous costumes.”\n– Trudy Garfunkel",
"“There’s no business like show business.”\n– Irving Berlin, 'Annie Get Your Gun'"]

module.exports = {
    getQuote : (specificQuote = -1) => {
        if(specificQuote < 0 || specificQuote >= quotes.length) {
            return quotes[Math.floor(Math.random() * quotes.length)];
        } else {
            return quotes[specificQuote];
        }
    }
}